language: rust
rust:
  - nightly

cache: cargo

script:
  - rustup install nightly-2019-05-14 && rustup default nightly-2019-05-14
  - rustc --version && rustup --version && cargo --version
  - cargo clean && cargo build --verbose --release
  - cargo test --verbose